package events

var ListenerEvent = Response{
	Description: []string{
		"Container struct for an event message sent by a controller.",
	},
	Message: Message{
		Name:    "listener event",
		MsgType: 0x20,
		Fields: []Field{
			{
				Name:        "controller",
				Type:        "uint32",
				Offset:      4,
				Tag:         "controller",
				Description: "controller serial number",
			},
			{
				Name:        "system date",
				Type:        "shortdate",
				Offset:      51,
				Tag:         "system-date",
				Description: "controller system date, e.g. 2025-07-21",
			},
			{
				Name:        "system time",
				Type:        "time",
				Offset:      37,
				Tag:         "system-time",
				Description: "controller system time, e.g. 13:25:47",
			},
			{
				Name:        "door 1 open",
				Type:        "bool",
				Offset:      28,
				Tag:         "door-1-open",
				Description: "door 1 open sensor",
			},
			{
				Name:        "door 2 open",
				Type:        "bool",
				Offset:      29,
				Tag:         "door-2-open",
				Description: "door 2 open sensor",
			},
			{
				Name:        "door 3 open",
				Type:        "bool",
				Offset:      30,
				Tag:         "door-3-open",
				Description: "door 3 open sensor",
			},
			{
				Name:        "door 4 open",
				Type:        "bool",
				Offset:      31,
				Tag:         "door-4-open",
				Description: "door 4 open sensor",
			},
			{
				Name:        "door 1 button",
				Type:        "bool",
				Offset:      32,
				Tag:         "door-1-button",
				Description: "door 1 button pressed",
			},
			{
				Name:        "door 2 button",
				Type:        "bool",
				Offset:      33,
				Tag:         "door-2-button",
				Description: "door 2 button pressed",
			},
			{
				Name:        "door 3 button",
				Type:        "bool",
				Offset:      34,
				Tag:         "door-3-button",
				Description: "door 3 button pressed",
			},
			{
				Name:        "door 4 button",
				Type:        "bool",
				Offset:      35,
				Tag:         "door-4-button",
				Description: "door 4 button pressed",
			},
			{
				Name:        "relays",
				Type:        "uint8",
				Offset:      49,
				Tag:         "relays",
				Description: "bitset of door unlock relay states",
			},
			{
				Name:        "inputs",
				Type:        "uint8",
				Offset:      50,
				Tag:         "alarm-inputs",
				Description: "bitset of alarm inputs",
			},
			{
				Name:        "system error",
				Type:        "uint8",
				Offset:      36,
				Tag:         "system-error",
				Description: "system error code",
			},
			{
				Name:        "special info",
				Type:        "uint8",
				Offset:      48,
				Tag:         "special-info",
				Description: "absolutely no idea",
			},
			{
				Name:        "event index",
				Type:        "uint32",
				Offset:      8,
				Tag:         "event-index",
				Description: "last event index",
			},
			{
				Name:        "event type",
				Type:        "uint8",
				Offset:      12,
				Tag:         "event-type",
				Description: "last event type",
			},
			{
				Name:        "event access granted",
				Type:        "bool",
				Offset:      13,
				Tag:         "event-granted",
				Description: "last event access granted",
			},
			{
				Name:        "event door",
				Type:        "uint8",
				Offset:      14,
				Tag:         "event-door",
				Description: "last event door",
			},
			{
				Name:        "event direction",
				Type:        "uint8",
				Offset:      15,
				Tag:         "event-direction",
				Description: "last event door direction (0: in, 1: out)",
			},
			{
				Name:        "event card",
				Type:        "uint32",
				Offset:      16,
				Tag:         "event-card",
				Description: "last event card number",
			},
			{
				Name:        "event timestamp",
				Type:        "optional datetime",
				Offset:      20,
				Tag:         "event-timestamp",
				Description: "last event timestamp",
			},
			{
				Name:        "event reason",
				Type:        "uint8",
				Offset:      27,
				Tag:         "event-reason",
				Description: "last event reason",
			},
			{
				Name:        "sequence no",
				Type:        "uint32",
				Offset:      40,
				Tag:         "sequence-no",
				Description: "packet sequence number",
			},
		},
	},
	Tests: []ResponseTest{
		{
			Name: "listener event",
			Response: []byte{
				0x17, 0x20, 0x00, 0x00, 0x78, 0x37, 0x2a, 0x18, 0x4e, 0x00, 0x00, 0x00, 0x02, 0x01, 0x03, 0x01,
				0xa1, 0x98, 0x7c, 0x00, 0x20, 0x22, 0x08, 0x23, 0x09, 0x47, 0x06, 0x2c, 0x00, 0x01, 0x00, 0x00,
				0x00, 0x00, 0x00, 0x01, 0x03, 0x09, 0x49, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
				0x27, 0x07, 0x09, 0x22, 0x08, 0x23, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
			},
			Expected: []Value{
				{
					Name:  "controller",
					Type:  "uint32",
					Value: 405419896,
				},
				{
					Name:  "system date",
					Type:  "shortdate",
					Value: "2022-08-23",
				},
				{
					Name:  "system time",
					Type:  "time",
					Value: "09:49:39",
				},
				{
					Name:  "door 1 open",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 2 open",
					Type:  "bool",
					Value: true,
				},
				{
					Name:  "door 3 open",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 4 open",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 1 button",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 2 button",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 3 button",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 4 button",
					Type:  "bool",
					Value: true,
				},
				{
					Name:  "relays",
					Type:  "uint8",
					Value: 0x07,
				},
				{
					Name:  "inputs",
					Type:  "uint8",
					Value: 0x09,
				},
				{
					Name:  "system error",
					Type:  "uint8",
					Value: 3,
				},
				{
					Name:  "special info",
					Type:  "uint8",
					Value: 39,
				},
				{
					Name:  "event index",
					Type:  "uint32",
					Value: 78,
				},
				{
					Name:  "event type",
					Type:  "uint8",
					Value: 2,
				},
				{
					Name:  "event access granted",
					Type:  "bool",
					Value: true,
				},
				{
					Name:  "event door",
					Type:  "uint8",
					Value: 3,
				},
				{
					Name:  "event direction",
					Type:  "uint8",
					Value: 1,
				},
				{
					Name:  "event card",
					Type:  "uint32",
					Value: 8165537,
				},
				{
					Name:  "event timestamp",
					Type:  "datetime",
					Value: "2022-08-23 09:47:06",
				},
				{
					Name:  "event reason",
					Type:  "uint8",
					Value: 44,
				},
				{
					Name:  "sequence no",
					Type:  "uint32",
					Value: 0,
				},
			},
		},
		{
			Name: "listener event v6_62",
			Response: []byte{
				0x19, 0x20, 0x00, 0x00, 0x78, 0x37, 0x2a, 0x18, 0x4e, 0x00, 0x00, 0x00, 0x02, 0x01, 0x03, 0x01,
				0xa1, 0x98, 0x7c, 0x00, 0x20, 0x22, 0x08, 0x23, 0x09, 0x47, 0x06, 0x2c, 0x00, 0x01, 0x00, 0x00,
				0x00, 0x00, 0x00, 0x01, 0x03, 0x09, 0x49, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
				0x27, 0x07, 0x09, 0x22, 0x08, 0x23, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
			},
			Expected: []Value{
				{
					Name:  "controller",
					Type:  "uint32",
					Value: 405419896,
				},
				{
					Name:  "system date",
					Type:  "shortdate",
					Value: "2022-08-23",
				},
				{
					Name:  "system time",
					Type:  "time",
					Value: "09:49:39",
				},
				{
					Name:  "door 1 open",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 2 open",
					Type:  "bool",
					Value: true,
				},
				{
					Name:  "door 3 open",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 4 open",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 1 button",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 2 button",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 3 button",
					Type:  "bool",
					Value: false,
				},
				{
					Name:  "door 4 button",
					Type:  "bool",
					Value: true,
				},
				{
					Name:  "relays",
					Type:  "uint8",
					Value: 0x07,
				},
				{
					Name:  "inputs",
					Type:  "uint8",
					Value: 0x09,
				},
				{
					Name:  "system error",
					Type:  "uint8",
					Value: 3,
				},
				{
					Name:  "special info",
					Type:  "uint8",
					Value: 39,
				},
				{
					Name:  "event index",
					Type:  "uint32",
					Value: 78,
				},
				{
					Name:  "event type",
					Type:  "uint8",
					Value: 2,
				},
				{
					Name:  "event access granted",
					Type:  "bool",
					Value: true,
				},
				{
					Name:  "event door",
					Type:  "uint8",
					Value: 3,
				},
				{
					Name:  "event direction",
					Type:  "uint8",
					Value: 1,
				},
				{
					Name:  "event card",
					Type:  "uint32",
					Value: 8165537,
				},
				{
					Name:  "event timestamp",
					Type:  "datetime",
					Value: "2022-08-23 09:47:06",
				},
				{
					Name:  "event reason",
					Type:  "uint8",
					Value: 44,
				},
				{
					Name:  "sequence no",
					Type:  "uint32",
					Value: 0,
				},
			},
		},
	},
}
