[package]
name = "uhppoted"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
chrono = "0.4"
futures = "0.3"
lazy_static = "1.4.0"
itertools = "0.10.3"
regex = "1.6.0"
ctrlc = "3.2.3"