name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ^3.10
      id: python

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        make build-all
        make go
        make rust
        make python
