name: zig

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.20
      id: go

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install zig
      uses: goto-bus-stop/setup-zig@v1
      with:
        version: 0.10.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build
      run: make zig
